name: CI/CD Pipeline with DAST

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests with coverage
      run: |
        python -m pytest --cov=app --cov-report=xml:coverage.xml --junitxml=test-results.xml
        
    - name: Run pylint
      run: |
        pylint app tests > pylint-report.txt || true

  sonarqube:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Download and Setup SonarQube Scanner
      shell: bash
      run: |
        # Install required dependencies
        sudo apt-get update
        sudo apt-get install -y unzip
        
        # Setup Java 17
        sudo apt-get install -y openjdk-17-jdk
        
        # Download and setup scanner
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
        unzip sonar-scanner-cli-4.8.0.2856-linux.zip
        sudo mv sonar-scanner-4.8.0.2856-linux /opt/sonar-scanner
        
        # Set permissions
        sudo chmod +x /opt/sonar-scanner/bin/sonar-scanner
        
        # Add to PATH
        echo "/opt/sonar-scanner/bin" >> $GITHUB_PATH
        
        # Verify installation
        echo "Verifying sonar-scanner installation..."
        echo "Java version:"
        java -version
        ls -l /opt/sonar-scanner/bin/sonar-scanner
        /opt/sonar-scanner/bin/sonar-scanner --version
        
    - name: Run SonarQube Scanner
      shell: bash
      env:
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
      run: |
        # Debug environment
        echo "Current PATH: $PATH"
        echo "Current directory: $(pwd)"
        echo "Java version:"
        java -version
        ls -la /opt/sonar-scanner/bin
        
        # Make the scanner script executable
        chmod +x /opt/sonar-scanner/bin/sonar-scanner
        
        # Run with bash explicitly
        bash /opt/sonar-scanner/bin/sonar-scanner \
          -Dsonar.projectKey=security-implementation \
          -Dsonar.sources=app \
          -Dsonar.tests=tests \
          -Dsonar.python.coverage.reportPaths=coverage.xml \
          -Dsonar.python.xunit.reportPath=test-results.xml \
          -Dsonar.python.pylint.reportPath=pylint-report.txt \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  dast:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Start the application
      env:
        FLASK_HOST: '0.0.0.0'
        FLASK_PORT: '5000'
        FLASK_DEBUG: 'False'
        DAST_SCAN: 'True'  # Enable DAST scanning mode
      run: |
        python run.py &
        echo "Waiting for application to start..."
        # Increase timeout and add better health check
        for i in {1..60}; do
          if curl -s http://localhost:5000 > /dev/null; then
            echo "Application is running!"
            break
          fi
          echo "Waiting for application to start... attempt $i"
          sleep 2
          if [ $i -eq 60 ]; then
            echo "Application failed to start within timeout"
            exit 1
          fi
        done
        
    - name: Prepare ZAP reports directory
      run: |
        # Create and set permissions for reports directory
        mkdir -p zap-reports
        chmod 777 zap-reports
        # Ensure the directory is empty
        rm -f zap-reports/*
        
    - name: Run OWASP ZAP DAST
      id: zap-scan
      run: |
        # Create ZAP config directory if it doesn't exist
        mkdir -p .zap
        
        # If rules.tsv doesn't exist, create a simple one
        if [ ! -f .zap/rules.tsv ]; then
          echo "Creating default rules.tsv file"
          echo "10016	IGNORE	.*" > .zap/rules.tsv
          echo "10020	IGNORE	.*" >> .zap/rules.tsv
        fi
        
        # Run ZAP scan with fixed configuration
        docker run --rm \
          -v "$(pwd)/zap-reports:/zap/wrk/:rw" \
          -v "$(pwd)/.zap/rules.tsv:/zap/rules.tsv:ro" \
          --network host \
          -t ghcr.io/zaproxy/zaproxy:stable \
          zap-baseline.py \
          -t http://localhost:5000 \
          -c /zap/rules.tsv \
          -J report.json \
          -w report.md \
          -r report.html \
          -a -I -j -d \
          -z "-config api.disablekey=true"
        
        ZAP_EXIT_CODE=$?
        echo "ZAP exit code: $ZAP_EXIT_CODE"
        
        # Accept exit codes 0 (success) and 2 (warnings found)
        if [ $ZAP_EXIT_CODE -eq 0 ] || [ $ZAP_EXIT_CODE -eq 2 ]; then
          echo "ZAP scan completed with exit code $ZAP_EXIT_CODE"
          # Verify reports were created
          if [ -f zap-reports/report.html ] && [ -f zap-reports/report.md ] && [ -f zap-reports/report.json ]; then
            echo "All report files were generated successfully"
            exit 0
          else
            echo "Some report files are missing:"
            ls -la zap-reports/
            exit 1
          fi
        else
          echo "ZAP scan failed with exit code $ZAP_EXIT_CODE"
          exit 1
        fi
        
    - name: Process and Display Scan Results
      run: |
        echo "=== ZAP Scan Summary ==="
        if [ -f zap-reports/report.md ]; then
          echo "Report found. Displaying summary:"
          # Extract and display the summary section
          awk '/^## Summary/,/^## /' zap-reports/report.md | head -n -1
          echo -e "\n=== Full Report Available ==="
          echo "The complete scan report is available in the workflow artifacts"
        else
          echo "No scan report was generated. Checking directory contents:"
          ls -la zap-reports/
          exit 1
        fi
        
    - name: Upload ZAP Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: zap-reports
        path: zap-reports/
        if-no-files-found: warn
        
    - name: Debug - Check application and container status
      if: always()
      run: |
        echo "=== Application Status ==="
        echo "Checking if application is still running..."
        curl -sv http://localhost:5000 || true
        echo "=== Network Status ==="
        netstat -tulpn | grep 5000 || true
        echo "=== Process Status ==="
        ps aux | grep python | grep -v grep || true
        echo "=== Directory Status ==="
        ls -la zap-reports/ || true

  deploy:
    needs: [test, dast]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to production
      run: |
        echo "Deploying to production..."
        # Add your deployment commands here