name: CI/CD Pipeline with DAST

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        python -m pytest

  dast:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Start the application
      env:
        FLASK_HOST: '0.0.0.0'
        FLASK_PORT: '5000'
        FLASK_DEBUG: 'False'
        DAST_SCAN: 'True'  # Enable DAST scanning mode
      run: |
        python run.py &
        echo "Waiting for application to start..."
        # Increase timeout and add better health check
        for i in {1..60}; do
          if curl -s http://localhost:5000 > /dev/null; then
            echo "Application is running!"
            break
          fi
          echo "Waiting for application to start... attempt $i"
          sleep 2
          if [ $i -eq 60 ]; then
            echo "Application failed to start within timeout"
            exit 1
          fi
        done
        
    - name: Prepare ZAP reports directory
      run: |
        mkdir -p zap-reports
        chmod 777 zap-reports
        
    - name: Run OWASP ZAP DAST
      id: zap-scan
      run: |
        # Create ZAP config directory if it doesn't exist
        mkdir -p .zap
        
        # If rules.tsv doesn't exist, create a simple one
        if [ ! -f .zap/rules.tsv ]; then
          echo "Creating default rules.tsv file"
          echo "10016	IGNORE	(Modern Web Application)	" > .zap/rules.tsv
          echo "10020	IGNORE	(X-Frame-Options header)	" >> .zap/rules.tsv
        fi
        
        # Run ZAP scan with fixed configuration
        docker run --rm \
          -v "$(pwd)/zap-reports:/zap/wrk/zap-reports:rw" \
          -v "$(pwd)/.zap/rules.tsv:/zap/rules.tsv:ro" \
          --network host \
          -t ghcr.io/zaproxy/zaproxy:stable \
          zap-baseline.py \
          -t http://localhost:5000 \
          -c /zap/rules.tsv \
          -J /zap/wrk/zap-reports/report.json \
          -w /zap/wrk/zap-reports/report.md \
          -r /zap/wrk/zap-reports/report.html \
          -a -I -j -d \
          -z "-config api.disablekey=true"
        
        ZAP_EXIT_CODE=$?
        echo "ZAP exit code: $ZAP_EXIT_CODE"
        
        # Accept exit codes 0 (success) and 2 (warnings found)
        if [ $ZAP_EXIT_CODE -eq 0 ] || [ $ZAP_EXIT_CODE -eq 2 ]; then
          echo "ZAP scan completed with exit code $ZAP_EXIT_CODE"
          exit 0
        else
          echo "ZAP scan failed with exit code $ZAP_EXIT_CODE"
          exit 1
        fi
        
    - name: Process and Display Scan Results
      run: |
        echo "=== ZAP Scan Summary ==="
        if [ -f zap-reports/report.md ]; then
          echo "Report found. Displaying summary:"
          # Extract and display the summary section
          awk '/^## Summary/,/^## /' zap-reports/report.md | head -n -1
          echo -e "\n=== Full Report Available ==="
          echo "The complete scan report is available in the workflow artifacts"
        else
          echo "No scan report was generated. Checking directory contents:"
          ls -la zap-reports/
          exit 1
        fi
        
    - name: Upload ZAP Reports
      uses: actions/upload-artifact@v4
      with:
        name: zap-reports
        path: zap-reports/
        if-no-files-found: warn
        
    - name: Debug - Check application and container status
      if: always()
      run: |
        echo "=== Application Status ==="
        echo "Checking if application is still running..."
        curl -sv http://localhost:5000 || true
        echo "=== Network Status ==="
        netstat -tulpn | grep 5000 || true
        echo "=== Process Status ==="
        ps aux | grep python | grep -v grep || true
        echo "=== Directory Status ==="
        ls -la zap-reports/ || true

  deploy:
    needs: [test, dast]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to production
      run: |
        echo "Deploying to production..."
        # Add your deployment commands here